# Owns the shell config formerly in the zsh/ stow package, retired in Phase 4.
#
# Bugs from the old files fixed by construction here:
#   - hardcoded /opt/homebrew zsh-syntax-highlighting path -> syntaxHighlighting
#   - /opt/homebrew/opt/{libpq,mysql-client}/bin on PATH -> dropped, use devShells
#   - the tec agent block appearing twice -> not carried over at all
#   - `mkd` reads markdown with glow; it does not mkdir
#   - `oops` was missing the leading `git`
#   - `cleanlocalbranches` used `|` where it meant `&&`, and left `^main` unquoted
#   - `ghcr-login` was a double-quoted alias, so $GITHUB_TOKEN was interpolated
#     at definition time (i.e. empty) -> it is a function now
#
# Not carried over, deliberately: `lc` (colorls), `goodmorning` (graphite) and
# `devswitch` (`dev tree`, a Shopify /opt/dev command the minidev fork does not
# have). All three are work-machine tooling.
{ lib, pkgs, ... }:

{
  programs.zsh = {
    enable = true;
    autosuggestion.enable = true;
    syntaxHighlighting.enable = true;
    enableCompletion = true;

    history = {
      size = 50000;
      save = 50000;
      ignoreDups = true;
      ignoreSpace = true;
      share = true;
    };

    oh-my-zsh = {
      enable = true;
      plugins = [ "git" "docker" "docker-compose" ];
    };

    plugins = [{
      name = "powerlevel10k";
      src = pkgs.zsh-powerlevel10k;
      file = "share/zsh-powerlevel10k/powerlevel10k.zsh-theme";
    }];

    shellAliases = {
      tf = "terraform";
      dps = ''docker ps --format "table {{.ID}}\t{{.Names}}\t{{.Status}}\t{{.Ports}}"'';
      inv = ''nvim $(fzf -m --preview="bat --color=always {}")'';
      fzc = ''fzf --height $(( $LINES / 2 )) -m --preview="bat --color=always {}"'';
      newtask = "git fetch --no-tags origin main && git checkout main";
      rebasemain = "git fetch --no-tags origin main && git rebase origin/main";
      gitdeletenontrackingbranches =
        "git branch -D $(git branch -vv | grep -v origin | awk '{print $1}')";

      # `|` here was a typo for `&&` — the old alias piped checkout's (empty)
      # stdout into `git branch`, so it ran regardless of whether checkout
      # succeeded. `^main` was unquoted and word-split by zsh.
      cleanlocalbranches =
        ''git checkout main && git branch | grep -v "^main" | xargs git branch -D'';

      # was `reset --soft HEAD~1` — no `git`.
      oops = "git reset --soft HEAD~1";

      set-secrets = "$(cat ~/.secrets)";

      matrix = ''LC_ALL=C tr -c "[:digit:]" " " < /dev/urandom | dd cbs=$COLUMNS conv=unblock | GREP_COLOR="1;32" grep --color "[^ ]"'';
    };

    # Split deliberately. p10k's instant prompt must be the FIRST thing in
    # the rc or it prints a warning and does nothing; home-manager's default
    # initContent slot lands well after `source $ZSH/oh-my-zsh.sh`.
    # mkOrder 500 == before everything, 1000 == the normal slot.
    initContent = lib.mkMerge [
      (lib.mkOrder 500 ''
        if [[ -r "''${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-''${(%):-%n}.zsh" ]]; then
          source "''${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-''${(%):-%n}.zsh"
        fi
      '')

      (lib.mkOrder 1000 ''
        # Secrets, if present. Never tracked in this repo.
        [ -f ~/.zshrc-secrets ] && source ~/.zshrc-secrets

        export GPG_TTY=$(tty)

        # Your own wizard output, not a stock preset. Generated by
        # `p10k configure` and kept in this repo so both hosts match --
        # it previously lived, untracked, at
        # ~/.oh-my-zsh/custom/themes/powerlevel10k/config/p10k-robbyrussell.zsh
        # where it had overwritten the preset of that name.
        # Re-run `p10k configure`, then copy ~/.p10k.zsh back over
        # nix/home/programs/zsh/p10k.zsh to change it.
        [[ -r ~/.p10k.zsh ]] && source ~/.p10k.zsh

        # Keep the herdr workspace sidebar aligned with this pane after each
        # prompt. Ported from zsh/.zshrc-functions in Phase 4; it had stopped
        # running at the mac migration, when that file stopped being sourced.
        autoload -Uz add-zsh-hook
        _herdr_active_pane_sidebar_precmd() {
          emulate -L zsh
          [[ -n "''${HERDR_PANE_ID:-}" ]] || return 0

          local script="$HOME/dotfiles/herdr/plugins/active-pane-sidebar/active_pane_sidebar.py"
          [[ -x "$script" ]] || return 0
          "$script" --pane-id "$HERDR_PANE_ID" >/dev/null 2>&1 &!
        }

        if (( ''${precmd_functions[(Ie)_herdr_active_pane_sidebar_precmd]} == 0 )); then
          add-zsh-hook precmd _herdr_active_pane_sidebar_precmd
        fi

        # Rebuild and activate this host's home-manager config.
        #   hms                  switch
        #   hms --show-trace     extra flags are passed through
        #
        # A timestamped backup suffix rather than a plain `bak`: -b only
        # writes a backup when a file is actually in the way, so this costs
        # nothing normally, but it stops a second collision from aborting the
        # switch because ~/.zshrc.bak already exists.
        hms() {
          local host
          # Keyed on hostname, not uname: there is more than one linux host
          # now. Must stay in step with `hosts` in flake.nix and the table in
          # helpers/lib/host.sh. The mac matches on uname because macOS
          # rewrites its hostname on some networks.
          case "$(hostname -s)" in
            vm-dev-01)            host=vm-dev-01 ;;
            infra-vm-coreapp-nuc) host=infra-nuc ;;
            *)
              if [[ "$(uname -s)" == Darwin ]]; then
                host=mac
              else
                print -u2 "hms: no host for $(hostname -s); see helpers/lib/host.sh"
                return 1
              fi
              ;;
          esac
          home-manager switch -b "bak-$(date +%Y%m%d%H%M%S)" \
            --flake "$HOME/dotfiles#gf@$host" "$@"
        }

        # Markdown CLI reader.
        mkd() { glow -t "$@" }

        schema_status() { opencode run "What's the status of migration: $@" }

        # A function, not an alias: the old double-quoted alias expanded
        # $GITHUB_TOKEN when the alias was defined, not when it was run.
        ghcr-login() {
          echo "$GITHUB_TOKEN" | docker login ghcr.io -u georgef-dev --password-stdin
        }

        source ${./cleanup.zsh}
      '')
    ];
  };

  home.file.".p10k.zsh".source = ./p10k.zsh;

  programs.fzf = {
    enable = true;
    enableZshIntegration = true;
  };
}
