#!/bin/bash
set -euo pipefail
CYAN='\033[0;36m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

printf '
                      __
                     / _|
                __ _| |_
               / _` |  _|
              | (_| | |
               \__, |_|
                __/ |
               |___/

Setting up...

'


if [ ! -d "$HOME/.oh-my-zsh/" ]; then
    echo "Installing Oh My Zsh"
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" || echo "Failed to install Oh My Zsh" >&2
    echo "Installing PowerLevel10k Them for Oh My Zsh"
    # PowerLevel 10k
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
fi

printf 'All set!' | lolcat
echo ; echo
